### ISSUE TITLE
QtXDG release

### ISSUE THREAD

**Issue by agaida** [lxde/lxqt-release-foo#4]
https://github.com/lxde/lxqt-release-foo/blob/master/announcements/2017-07-27-libqtxdg-3.0.0.md

@luis-pereira @tsimonq2 - please have a look and add things i might have forgotten - i really want to roll that out :D

**Comment by tsimonq2** [comment]
I made a few grammar corrections (trivial enough that I felt confident in just pushing), and a bit later I'll skim the `CHANGELOG` file for any more notable changes.

Thanks Alf!

**Comment by luis-pereira** [comment]
@agaida IMO this ones are worth mentioning:
lxde/libqtxdg@7486887af74943c08e7a350c28bc415efc0e259c
lxde/libqtxdg@2d18950ffc13072187e2cd988b9e1ca05297a2b6
lxde/libqtxdg@a797a54b0c42c344a1071554c37c2198e0caf1d1

**Comment by agaida** [comment]
indeed, thank you very much
